### ISSUE TITLE
IS0501: Testing mqtt receiver results in KeyError

### ISSUE THREAD

**Issue by jasperpeeters** [AMWA-TV/nmos-testing#500]
Testing a mqtt receiver against the IS0501 testsuite throws a bunch of `Uncaught exception. Please report the traceback from the terminal to https://github.com/amwa-tv/nmos-testing/issues. 'destination_port' `. 

Traceback: 
```
 * Running test_37
Traceback (most recent call last):
  File "/home/jasper/git/github/nmos-testing/nmostesting/GenericTest.py", line 140, in execute_test
    self.result.append(method(test))
  File "/home/jasper/git/github/nmos-testing/nmostesting/suites/IS0501Test.py", line 770, in test_37
    valid, response = self.check_bulk_stage("receiver", self.receivers)
  File "/home/jasper/git/github/nmos-testing/nmostesting/suites/IS0501Test.py", line 980, in check_bulk_stage
    valid, response = self.is05_utils.generate_changeable_param(port, portInst, self.transport_types[portInst])
  File "/home/jasper/git/github/nmos-testing/nmostesting/IS05Utils.py", line 427, in generate_changeable_param
    return self.generate_destination_ports(port, portId)
  File "/home/jasper/git/github/nmos-testing/nmostesting/IS05Utils.py", line 445, in generate_destination_ports
    if "enum" in entry['destination_port']:
KeyError: 'destination_port'
```

I'm really not sure why this did not pop up earlier on our side..

During a couple tests (test_24, test_26, test_28, test_30 and test_37) at some point a changeable parameter is chosen depending on the transport type. 

Until now this is the corresponding piece of code: 
```
    def generate_changeable_param(self, port, portId, transportType):
        """Use a port's constraints to generate a changeable parameter"""
        if transportType == "urn:x-nmos:transport:websocket":
            return self.generate_connection_uris(port, portId)
        else:
            return self.generate_destination_ports(port, portId)
```

For MQTT receivers there is no `destination_port`, neither in the constraints nor in the `/staged` or `/active` params.

Side issue here: the corresponding piece of code did not catch `KeyErrors` in such cases.

**Comment by jasperpeeters** [comment]
Solved by https://github.com/AMWA-TV/nmos-testing/pull/501
