### ISSUE TITLE
IS-05 - Tests 25,27, 29... list index out of range

### ISSUE THREAD

**Issue by jfgagnon12** [AMWA-TV/nmos-testing#516]
Traceback (most recent call last):
  File "E:\Other\github\nmos\nmos-testing\nmostesting\GenericTest.py", line 140, in execute_test
    self.result.append(method(test))
  File "E:\Other\github\nmos\nmos-testing\nmostesting\suites\IS0501Test.py", line 126, in test_09_01
    valid, result = self.is05_utils.check_sdp_matches_params(sender)
  File "E:\Other\github\nmos\nmos-testing\nmostesting\IS05Utils.py", line 667, in check_sdp_matches_params
    tp_compare.append("m=" + sdp_media_sections[0])
IndexError: list index out of range

**Comment by garethsb-sony** [comment]
I think that implies the SDP has no `m=` lines. Can you show the SDP file?
We should report this as an error rather than an exception of course.

**Comment by garethsb-sony** [comment]
No more info, so closing
