### ISSUE TITLE
zeroconf 0.27.0

### ISSUE THREAD

**Issue by TobiasThierolf** [AMWA-TV/nmos-testing#538]
Hello there,

we had some issues with the python zeroconf module installed on a windows machine. 

My initial setup, a linux machine with an older version of the nmos-testing project and also older versions of the python modules worked fine for almost all tests. Our QA department installed the current version of this project ~1 week ago and they didn't manage to run it.

When I checked the output of the nmos-test.py there were some asserts happening on many of the test in the IS-04 Node test, other tests are affected as well. 

Here is one example:
```
Traceback (most recent call last):
  File "C:\Users\XXX\Documents\nmos-testing-master\nmostesting\GenericTest.py", line 140, in execute_test
    self.result.append(method(test))
  File "C:\Users\XXX\Documents\nmos-testing-master\nmostesting\suites\IS0401Test.py", line 930, in test_16_01
    self.do_registry_basics_prereqs()
  File "C:\Users\XXX\Documents\nmos-testing-master\nmostesting\suites\IS0401Test.py", line 169, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0])
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zeroconf\__init__.py", line 2374, in register_service
    self._broadcast_service(info)
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zeroconf\__init__.py", line 2400, in _broadcast_service
    DNSService(
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zeroconf\__init__.py", line 662, in __init__
    DNSRecord.__init__(self, name, type_, class_, ttl)
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zeroconf\__init__.py", line 459, in __init__
    self._expiration_time = self.get_expiration_time(100)
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\zeroconf\__init__.py", line 486, in get_expiration_time
    return self.created + (percent * self.ttl * 10)
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

I managed to get rid of those asserts by downgrading the zeroconf module from 0.27.0 to 0.24.4 and zeroconf-monkey from 1.0.0 to 0.1.0. I did not test with zeroconf 0.25.0 and zeroconf-monkey 1.0.0 yet.

In the requirements.txt only the zeroconf-monkey 1.0.0 is listed and this has the requirements zeroconf >=0.25.0 which caused 0.27.0 to be installed on our system. I don't really know how to manage dependencies in python but wouldn't it be better to specify zeroconf==<version> for a version that is validated? Otherwise every zeroconf update would possibly introduce changes that might fail.

Regards
Tobias

**Comment by garethsb-sony** [comment]
I have reproduced this. I'll investigate how to fix this. There are some features coming to python-zeroconf that may be useful so I would prefer not to pin a particular version. We hope that dependencies follow semantic versioning and version **0.n+1** should be backwards compatible with version **0.n**, but that isn't always the case unfortunately.

**Comment by garethsb-sony** [comment]
The (first) issue is the removal of a constructor argument in `ServiceInfo` - https://github.com/jstasiak/python-zeroconf/commit/ab72aa8e5a6a83e50d24d7fb187e8fa8a549a847. I think I can work round this, maintaining compatibility as >=0.25.0.
