### ISSUE TITLE
Changes to compare json in TestHelper.py breaks IS05 tests 9 and 10

### ISSUE THREAD

**Issue by jimgii** [AMWA-TV/nmos-testing#553]
The change made on June 30 causes: Uncaught exception. Please report the traceback from the terminal to https://github.com/amwa-tv/nmos-testing/issues. Non-JSON type

 * Running test_09
Traceback (most recent call last):
  File "/home/jimg/work/nmos/nmos-testing/nmostesting/GenericTest.py", line 141, in execute_test
    self.result.append(method(test))
  File "/home/jimg/work/nmos/nmos-testing/nmostesting/suites/IS0501Test.py", line 109, in test_09
    valid, response = self.is05_utils.check_params_match("senders", self.senders)
  File "/home/jimg/work/nmos/nmos-testing/nmostesting/IS05Utils.py", line 623, in check_params_match
    if TestHelper.compare_json(constraintParams, stagedParams):
  File "/home/jimg/work/nmos/nmos-testing/nmostesting/TestHelper.py", line 132, in compare_json
    return JsonType.eq(json1, json2)
  File "/home/jimg/work/nmos/nmos-testing/nmostesting/TestHelper.py", line 59, in eq
    return cls._cmp_json(json1, json2) == 0
  File "/home/jimg/work/nmos/nmos-testing/nmostesting/TestHelper.py", line 68, in _cmp_json
    t1 = cls.of(json1)
  File "/home/jimg/work/nmos/nmos-testing/nmostesting/TestHelper.py", line 55, in of
    raise TypeError('Non-JSON type')
TypeError: Non-JSON type

The JSON type causing the problem is a dictionary keys view.

**Comment by garethsb-sony** [comment]
Ah, sorry. I'll double check that.
