### ISSUE TITLE
test_26 TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by matthewdicken** [AMWA-TV/nmos-testing#603]
* Running test_26
Traceback (most recent call last):
  File "/home/obe/nmos-testing/nmostesting/GenericTest.py", line 161, in execute_test
    self.result.append(method(test))
  File "/home/obe/nmos-testing/nmostesting/suites/IS0501Test.py", line 626, in test_26
    self.transport_types[receiver])
  File "/home/obe/nmos-testing/nmostesting/IS05Utils.py", line 294, in check_activation
    return activationMethod(port, portId, stagedParams, paramName)
  File "/home/obe/nmos-testing/nmostesting/IS05Utils.py", line 248, in check_perform_immediate_activation
    return self._check_perform_activation(port, portId, stagedParams, changedParam)
  File "/home/obe/nmos-testing/nmostesting/IS05Utils.py", line 163, in _check_perform_activation
    if re.match("^[0-9]+:[0-9]+$", stagedActivation) is not None:
  File "/usr/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

**Comment by garethsb-sony** [comment]
Thanks. We should definitely change that to a proper error to help people returning `"activation_time": null`.
