### ISSUE TITLE
Uncaught exception under test_07 from suite IS-05 Interaction with IS-04

### ISSUE THREAD

**Issue by VentuzVictor** [AMWA-TV/nmos-testing#611]
Hi.

I found this exception when running the test_07 from suite IS-05 Interaction with IS-04.

```
Traceback (most recent call last):
  File "C:\Users\Victor\source\repos\nmos-testing-tool\nmos-testing-master\nmostesting\GenericTest.py", line 148, in execute_test
    self.result.append(method(test))
  File "C:\Users\Victor\source\repos\nmos-testing-tool\nmos-testing-master\nmostesting\suites\IS0502Test.py", line 437, in test_07
    valid, response = self.activate_check_parked(resource_type, resource_subset)
  File "C:\Users\Victor\source\repos\nmos-testing-tool\nmos-testing-master\nmostesting\suites\IS0502Test.py", line 211, in activate_check_parked
    if is04_resource["id"] == is05_resource:
TypeError: string indices must be integers
 * Running test_08
Traceback (most recent call last):
  File "C:\Users\Victor\source\repos\nmos-testing-tool\nmos-testing-master\nmostesting\GenericTest.py", line 148, in execute_test
    self.result.append(method(test))
  File "C:\Users\Victor\source\repos\nmos-testing-tool\nmos-testing-master\nmostesting\suites\IS0502Test.py", line 463, in test_08
    valid, response = self.activate_check_parked(resource_type, resource_subset)
  File "C:\Users\Victor\source\repos\nmos-testing-tool\nmos-testing-master\nmostesting\suites\IS0502Test.py", line 211, in activate_check_parked
    if is04_resource["id"] == is05_resource:
TypeError: string indices must be integers
```

**Comment by andrewbonney** [comment]
I suspect this error means that one of your IS-04 Node's resources (either `/senders` or `/receivers`) has an entry in the list which is a string rather than an object. We could possibly add some extra validation in the tests to check that the IS-04 resources 'look' valid, but that's really what the IS-04 tests are for.

I'd recommend checking that your Node is correctly passing the IS-04 tests, and if it is then maybe when running the IS-05 + IS-04 tests check that there isn't anything unusual appearing at the `/senders` or `/receivers` resource for your IS-04 Node when the tests execute.
