### ISSUE TITLE
Uncaught Exception found in test_17 under the test suite IS-05 Interaction with IS-04

### ISSUE THREAD

**Issue by VentuzVictor** [AMWA-TV/nmos-testing#612]
```
Traceback (most recent call last):
  File "C:\Users\Victor\source\repos\nmos-testing-tool\nmos-testing-master\nmostesting\GenericTest.py", line 148, in execute_test
    self.result.append(method(test))
  File "C:\Users\Victor\source\repos\nmos-testing-tool\nmos-testing-master\nmostesting\suites\IS0502Test.py", line 1045, in test_17
    is04_clock = clock_map[source["clock_name"]]
KeyError: 'clk0'
 * Running test_18
192.168.3.137 - - [15/Jun/2021 14:14:01] "←[37mPOST / HTTP/1.1←[0m" 200 - "http://192.168.3.137:5000" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
 * Running test_17
Traceback (most recent call last):
  File "C:\Users\Victor\source\repos\nmos-testing-tool\nmos-testing-master\nmostesting\GenericTest.py", line 161, in execute_test
    self.result.append(method(test))
  File "C:\Users\Victor\source\repos\nmos-testing-tool\nmos-testing-master\nmostesting\suites\IS0502Test.py", line 1045, in test_17
    is04_clock = clock_map[source["clock_name"]]
KeyError: 'clk1' 
```

**Comment by garethsb** [comment]
That suggests the Source clocks 'clk0' and 'clk1' are not in the Nodes `clocks` array, which is invalid.
If so, IS-04-01 `test_18` ought to have reported **FAIL**?

That said, IS-05-02 `test_17` didn't ought to raise an exception in this case, but report the error, like it already does for the case of the Source not having a `clock_name`.

Looks like there are some other opportunities for uncaught `KeyError` in that test case, e.g. `source = source_map[flow["source_id"]]`, which could be dealt with at the same time.

**Comment by VentuzVictor** [comment]
Hi Gareth.

Thanks for your answer.

Just to confirm, yes, when the uncaught exception is thrown under the `test_17 ` from **IS-05 Interaction with IS-04**, IS-04-01 `test_18 `reports fail.

**Comment by garethsb** [comment]
As Andrew said in the other recent issue that I'd missed, it's a good idea to get a clean sheet from the **IS-04-01** and **IS-05-01** test suites before trying the combination one, **IS-05-02**. As test authors it's very easy to unintentionally make assumptions of that sort (and similarly I expect in the case of **IS-07-02** and **IS-08-02**).
