### ISSUE TITLE
[IS-05] TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kierank** [AMWA-TV/nmos-testing#624]
```
Traceback (most recent call last):
  File "/home/obe/nmos-testing/nmostesting/IS05Utils.py", line 58, in check_num_legs
    stagedParams = staged['transport_params']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/obe/nmos-testing/nmostesting/GenericTest.py", line 148, in execute_test
    self.result.append(method(test))
  File "/home/obe/nmos-testing/nmostesting/suites/IS0501Test.py", line 842, in test_38
    valid, response = self.is05_utils.check_num_legs(url, "sender", sender)
  File "/home/obe/nmos-testing/nmostesting/IS05Utils.py", line 61, in check_num_legs
    type(staged),
TypeError: 'str' object is not callable
 * Running test_39
 * Running test_40
 * Running test_41
Traceback (most recent call last):
  File "/home/obe/nmos-testing/nmostesting/GenericTest.py", line 148, in execute_test
    self.result.append(method(test))
  File "/home/obe/nmos-testing/nmostesting/suites/IS0501Test.py", line 918, in test_41
    if len(response["transport_params"]) == 2:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by garethsb** [comment]
Thanks for the report. Presumably you have `"transport_params": null` in a _/staged_ endpoint, which is invalid. Will look at reporting the error properly.
