### ISSUE TITLE
IS-04 Node Test 24_01 uncaught exception: ZeroDivisionError

### ISSUE THREAD

**Issue by matthewdicken** [AMWA-TV/nmos-testing#673]
Traceback (most recent call last):
  File "/home/obe/matt/nmos-testing/nmostesting/GenericTest.py", line 162, in execute_test
    self.result.append(method(test))
  File "/home/obe/matt/nmos-testing/nmostesting/suites/IS0401Test.py", line 1566, in test_24_01
    (flow_rate["numerator"] * source_rate["denominator"])):
ZeroDivisionError: integer division or modulo by zero

**Comment by garethsb** [comment]
Thanks for the report - please see if #674 helps.
