### ISSUE TITLE
nmos-testing exits running easy-nmos

### ISSUE THREAD

**Issue by RickHuyett** [AMWA-TV/nmos-testing#680]
Hi. I am having trouble getting the nmos-testing to run using the easy-nmos docker-compose container.  Am running on Ubuntu 22.4.

The nmos-registry continues to work and I am able to see our senders and receivers with NMOS Explorer.  However the nmos-testing exits after failing to clone from github.  Fwiw I am able to get to github with the Firefox browser.  Below are the relevant lines from the easy-nmos on-screen log.  Also I have the ufw firewall currently disabled.  I suspect it is a configuration issue on my end since I am relatively new to the linux environment but nothing I have found in my searches has fixed this issue.

nmos-testing   |  * Initialising specification repositories...
nmos-testing   |  * Initialising repository 'nmos-discovery-registration'
nmos-testing   | /usr/local/lib/python3.6/dist-packages/authlib/jose/rfc7517/_cryptography_key.py:1: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
nmos-testing   |   from cryptography.x509 import load_pem_x509_certificate
nmos-testing   | Traceback (most recent call last):
nmos-testing   |   File "nmos-test.py", line 19, in <module>
nmos-testing   |     NMOSTesting.main(sys.argv)
nmos-testing   |   File "/home/nmos-testing/nmostesting/NMOSTesting.py", line 1061, in main
nmos-testing   |     init_spec_cache()
nmos-testing   |   File "/home/nmos-testing/nmostesting/NMOSTesting.py", line 605, in init_spec_cache
nmos-testing   |     repo = git.Repo.clone_from('https://github.com/AMWA-TV/' + repo_data["repo"] + '.git', path)
nmos-testing   |   File "/usr/local/lib/python3.6/dist-packages/git/repo/base.py", line 1111, in clone_from
nmos-testing   |     return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
nmos-testing   |   File "/usr/local/lib/python3.6/dist-packages/git/repo/base.py", line 1049, in _clone
nmos-testing   |     finalize_process(proc, stderr=stderr)
nmos-testing   |   File "/usr/local/lib/python3.6/dist-packages/git/util.py", line 370, in finalize_process
nmos-testing   |     proc.wait(**kwargs)
nmos-testing   |   File "/usr/local/lib/python3.6/dist-packages/git/cmd.py", line 447, in wait
nmos-testing   |     raise GitCommandError(remove_password_if_present(self.args), status, errstr)
nmos-testing   | git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
nmos-testing   |   cmdline: git clone -v https://github.com/AMWA-TV/nmos-discovery-registration.git cache/is-04
nmos-testing   |   stderr: 'Cloning into 'cache/is-04'...
nmos-testing   | fatal: unable to access 'https://github.com/AMWA-TV/nmos-discovery-registration.git/': Failed to connect to github.com port 443: Network is unreachable
nmos-testing   | '
nmos-testing exited with code 1

**Comment by garethsb** [comment]
I suspect problem is most likely in the easy-nmos network config. For example, we've seen issues when the host network gateway wasn't at the common `x.x.x.1` (see https://github.com/rhastie/easy-nmos/issues/18).

I would like to make the external network dependency optional by implementing https://github.com/AMWA-TV/nmos-testing/issues/661. If you can't get Internet access working from the containers, adding the cache manually is another option.
