### ISSUE TITLE
A fresh clone yields: "ImportError: cannot import name 'escape' from 'jinja2'" when attempting to run nmos-test

### ISSUE THREAD

**Issue by cristian-recoseanu** [AMWA-TV/nmos-testing#731]
These are the debug messages:
```
Traceback (most recent call last):
  File ".\nmos-test.py", line 16, in <module>
    from nmostesting import NMOSTesting
  File "C:\Source code\NMOS\nmos-testing-fresh\nmostesting\NMOSTesting.py", line 36, in <module>
    from flask import Flask, render_template, flash, request, make_response, jsonify
  File "C:\Users\cristian.recoseanu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (C:\Users\cristian.recoseanu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jinja2\__init__.py)
```
An initial research seems to point at this as being the cause:
https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2

This probably means the fix is to bump the version of Flask in the requirements file.

**Comment by garethsb** [comment]
Must have had a site package install of flask 1.x.y lying around. Bumping requirement to `flask>=2` seems to fix things. 👍
