### ISSUE TITLE
[IS-04-02] test_23_1 Not working on a v1.0 node resource.

### ISSUE THREAD

**Issue by MongareAlex** [AMWA-TV/nmos-testing#781]
The test seems to be querying on a description attribute which is not available on a v1.0 node.

Here is the Traceback (most recent call last):  

`File "C:Sandbox\nmos-testing-master (1)\nmos-testing-master\nmostesting\GenericTest.py", line 164, in execute_test
    self.result.append(method(test))
                       ^^^^^^^^^^^^
  File "C:Sandbox\nmos-testing-master (1)\nmos-testing-master\nmostesting\suites\IS0402Test.py", line 1422, in test_23_1
    if post_data["description"] != node_ids[0]:
       ~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'description' `

**Comment by garethsb** [comment]
Thanks for the report. You are correct. IS-04 v1.0 Node resources didn't have `description`. And the Query API didn't define _any_ `queryParameters` in the RAML. A Registry may quite correctly not support queries on this attribute at v1.0.

Probably the simplest fix is to use mock Device resources in these tests rather than Node resources.

Since IS-04 v1.3 is already 3.5 years old, and v1.2 (minimum for JT-NM Tested) is nearly 5 years old, this issue may not get fixed immediately.

**Comment by MongareAlex** [comment]
Alright, will consider mocking with a device resource.

**Comment by garethsb** [comment]
Reopening as should be fixed.
