### ISSUE TITLE
IS-04 Node API -  Uncaught Exceptions when using the testing suite version 16157f5

### ISSUE THREAD

**Issue by hexeninverter** [AMWA-TV/nmos-testing#831]
Hello Gareth,

When testing our NMOS implementation using the latest version of the testing suite, I get the following FAILs with reason:

`Uncaught exception. Please report the traceback from the terminal to https://github.com/AMWA-TV/nmos-testing/issues. Zeroconf.register_service() got an unexpected keyword argument 'strict'`

for the following IS-04 Node API tests:

+ tests 01 to 12_01, 15 to 16_01 and test 21

I am using mDNS-SD for the testing of our device.
 
This has never happened before, the previous versions of the testing suite always delivered a PASS on the same version of our NMOS implementation.

Here are the tracebacks from the terminal:

* Running test_01
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 290, in test_01
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_01_01
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 308, in test_01_01
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_02

 * Running test_02_01

 * Running test_03
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 355, in test_03
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_03_01
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 393, in test_03_01
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_04
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 563, in test_04
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'
 * Running test_05
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 576, in test_05
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_07
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 640, in test_07
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_07_01
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 650, in test_07_01
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_08
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 658, in test_08
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_08_01
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 668, in test_08_01
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_09
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 676, in test_09
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_09_01
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 686, in test_09_01
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_10
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 694, in test_10
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_10_01
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 704, in test_10_01
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_11
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 712, in test_11
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_11_01
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 722, in test_11_01
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

 * Running test_12

 * Running test_12_01
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 789, in test_12_01
    node_list = self.collect_mdns_announcements()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 2163, in collect_mdns_announcements
    self.zc.register_service(registry_info, strict=self._strict_service_name(registry_info))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'`

* Running test_15
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 957, in test_15
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'
 * Running test_16
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 985, in test_16
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'
 * Running test_16_01
Traceback (most recent call last):
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\GenericTest.py", line 155, in execute_test
    self.result.append(method(test))
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 1007, in test_16_01
    self.do_registry_basics_prereqs()
  File "C:\Users\PHadacek\Desktop\nmos-testing\nmostesting\suites\IS0401Test.py", line 195, in do_registry_basics_prereqs
    self.zc.register_service(registry_mdns[0], strict=self._strict_service_name(registry_mdns[0]))
TypeError: Zeroconf.register_service() got an unexpected keyword argument 'strict'

**Comment by garethsb** [comment]
You probably just need to upgrade required dependencies, to get a sufficiently recent version of zeroconf. Something like:

```
pip install -r requirements.txt
```

**Comment by hexeninverter** [comment]
Yes, that has worked! I had forgotten to reboot my system after installing....
