### ISSUE TITLE
Str object has no status_code

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-testing#91]
```
* Running test_31
 * ERROR: 'str' object has no attribute 'status_code'
192.168.200.43 - - [15/Jan/2019 18:15:30] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ipstudio-admin/nmos-testing/nmos-test.py", line 218, in index_page
    raise ex
  File "/home/ipstudio-admin/nmos-testing/nmos-test.py", line 215, in index_page
    result = test_obj.run_tests(test_selection)
  File "/home/ipstudio-admin/nmos-testing/GenericTest.py", line 133, in run_tests
    self.execute_tests(test_name)
  File "/home/ipstudio-admin/nmos-testing/GenericTest.py", line 101, in execute_tests
    self.result.append(method())
  File "/home/ipstudio-admin/nmos-testing/IS0402Test.py", line 809, in test_31
    return test.FAIL("Query API returned an unexpected response: {}".format(r.status_code, r.text))
AttributeError: 'str' object has no attribute 'status_code'

```

**Comment by andrewbonney** [comment]
Looks like there are a few cases of this. If 'valid' returns False, then the second object is a string rather than a Requests Response. Need to scan the codebase for 'if not valid' to catch any other cases.

**Comment by jasperpeeters** [comment]
Yes I looked at this already at the workshop. I've made some local fixes, but not pushed yet. Will come back to this tomorrow with a fix

**Comment by andrewbonney** [comment]
Ha, saw your response too late. Feel free to use this or your local version as appropriate.

**Comment by jasperpeeters** [comment]
Never mind :)
Your changes look good, I just checked them in detail. :+1:
